seminal2024/quiz_app/urls.py
from django.urls import path
from . import views

app_name = "quiz_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("registration/", views.registration, name='registration'),
    path("Quiz_list", views.page_list, name="page_list"),
    path("Quiz_list/<uuid:id>/", views.quiz_detail, name="quiz_detail"),
    path("Quiz_list/<uuid:id>/update/", views.quiz_update, name="quiz_update"),
    path("Quiz/", views.quiz, name="quiz"),
    path("Quiz_result", views.quiz_result, name="quiz_result")
]

seminal2024/seminal2024/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quiz_app.urls")),
]

seminal2024/quiz_app/models.py
from django.db import models
import uuid

# Create your models here.
class Page(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4,editable=False, verbose_name="ID")
    source = models.CharField(max_length=500, verbose_name='出典')
    source_text = models.TextField(max_length=5000, verbose_name="出典元本文", default='')
    quiz_text = models.TextField(max_length=1000, verbose_name='クイズ')
    correct = models.CharField(max_length=100, verbose_name='正解')
    incorrect_1 = models.CharField(max_length=100, verbose_name='不正解1')
    incorrect_2 = models.CharField(max_length=100, verbose_name='不正解2')

    def __str__(self):
        return self.quiz_text

seminal2024/quiz_app/forms.py
from django.forms import ModelForm
from .models import Page

class UploadFileForm(ModelForm):
    class Meta:
        model = Page
        fields = ["source", "source_text", "quiz_text", "correct", "incorrect_1", "incorrect_2"]

seminal2024/quiz_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse
from .forms import UploadFileForm
from .models import Page
import random


# Create your views here.
class IndexView(View):
    def get(self, request):
        return render(request, "main/index.html")


class RegistrationQuiz(View):
    def get(self, request):
        registration = UploadFileForm()
        return render(
            request, "main/registration_quiz.html", {"registration": registration}
        )

    def post(self, request):
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("quiz_app:index")
        return render(request, "main/registration_quiz.html", {"form": form})


class QuizList(View):
    def get(self, request):
        page_list = Page.objects.all()
        return render(request, "main/quiz_list.html", {"page_list": page_list})


class QuizDetail(View):
    def get(self, request, id):
        quiz = get_object_or_404(Page, id=id)
        return render(request, "main/quiz_detail.html", {"quiz": quiz})


class Quiz(View):
    def get(self, request):
        # 初めてのアクセス時、セッション内に'displayed_data'キーが存在しない場合は空のリストを作成
        if "displayed_data" not in request.session:
            request.session["displayed_data"] = []

        # URLのクエリパラメータに'change_data'が含まれているかをチェック
        if 'change_data' in request.GET:
            # セッションのランダムデータをリセット
            if 'random_data' in request.session:
                del request.session['random_data']
            # セッションに'change_data'フラグを設定
            request.session['change_data_flag'] = True
            # クエリパラメータをとり沿いたURLにリダイレクト
            return redirect(reverse('quiz_app:quiz'))
        
        # 'change_data_flag'がセッション内に存在する場合、新しいデータをDBから取得
        if 'change_data_flag' in request.session:
            del request.session['change_data_flag']
            # 引き出すデータは、既に表示したデータID以外を取得
            all_data = list(
                Page.objects.exclude(id__in=request.session["displayed_data"])
            )
            # all_data = []
            if all_data:
                random_data = random.choice(all_data)
                request.session["displayed_data"].append(str(random_data.id))
                request.session["random_data"] = {
                    "source": random_data.source,
                    "source_text": random_data.source_text,
                    "quiz_text": random_data.quiz_text,
                    "correct": random_data.correct,
                    "incorrect_1": random_data.incorrect_1,
                    "incorrect_2": random_data.incorrect_2,
                }
            else:
                return redirect(reverse('quiz_app:quiz_result'))
        else:
            # セッション内に'random_data'が存在しない場合、新しいデータを取得
            if "random_data" not in request.session:
                all_data = list(
                    Page.objects.exclude(id__in=request.session["displayed_data"])
                )
                if all_data:
                    random_data = random.choice(all_data)
                    request.session["displayed_data"].append(str(random_data.id))
                    request.session["random_data"] = {
                        "source": random_data.source,
                        "source_text": random_data.source_text,
                        "quiz_text": random_data.quiz_text,
                        "correct": random_data.correct,
                        "incorrect_1": random_data.incorrect_1,
                        "incorrect_2": random_data.incorrect_2,
                    }
                else:
                    return redirect(reverse('quiz_app:result'))
            else:
                # セッションからデータを取得
                random_data = request.session["random_data"]

        return render(request, "main/quiz01.html", {"data": random_data})
    
class QuizResult(View):
    def get(self, request):
        return render(request, 'main/quiz_result.html')


class QuizUpdate(View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = UploadFileForm(instance=page)
        return render(request, "main/quiz_update.html", {"form": form})

    def post(self, request, id):
        page = get_object_or_404(Page, id=id)
        form = UploadFileForm(request.POST, request.FILES, instance=page)
        if form.is_valid():
            form.save()
            return redirect("quiz_app:quiz_detail", id=id)
        return render(request, "main/quiz_detail.html", {"form": form})


index = IndexView.as_view()
registration = RegistrationQuiz.as_view()
page_list = QuizList.as_view()
quiz_detail = QuizDetail.as_view()
quiz = Quiz.as_view()
quiz_result  = QuizResult.as_view()
quiz_update = QuizUpdate.as_view()

seminal2024/templates/base/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>時事ニュースクイズサイト</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/quiz_style.css' %}">
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

seminal2024/templates/main/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>時事ニュースAIクイズ</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/quiz_title.css' %}">
</head>

<body>
    <div class="container">
        <div id="header">
            <h1>時事ニュースAIクイズ</h1>
        </div>
        <div class="content">
            <p class="btn"><a href="{% url 'quiz_app:quiz' %}">はじめる</a></p>
            <p class="btn"><a href="{% url 'quiz_app:registration' %}">クイズ登録</a></p>
            <p class="btn"><a href="{% url 'quiz_app:page_list' %}">クイズ一覧</a></p>
        </div>
    </div>
</body>

</html>

seminal2024/templates/main/newsquiz.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>時事ニュースクイズサイト</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/newsquiz.css' %}">
</head>

<body>
    <div class="container">
        <div id="header">
            <h1>時事ニュースクイズ</h1>
        </div>
        <div class="content">
            <div id="h2">
                <h2>クイズ一覧</h2>
            </div>
            <div id="ul">
                <li class="clickable" id="quiz01"><a href="{% url 'quiz01.html' %}">見出しをクリックすると、URLに飛ぶ</a></li>
                <li class="clickable" id="myText">見出しをクリックすると、URLに飛ぶ</li>
                <li class="clickable" id="myText">見出しをクリックすると、URLに飛ぶ</li>
                <li class="clickable" id="myText">見出しをクリックすると、URLに飛ぶ</li>
                <li class="clickable" id="myText">見出しをクリックすると、URLに飛ぶ</li>
                </ul>
            </div>
        </div>
    </div>
{% load static %}
<script src="{% static 'js/newsquiz.js' %}"></script>
</body>

</html>

seminal2024/templates/main/quiz.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>時事ニュースクイズサイト</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/quiz_title.css' %}">
</head>

<body>
    <div class="container">
        <div id="header">
            <h1>aaaaaaaaaaaaaaaaaa</h1>
        </div>
        <div class="content">
            <h2>{{ random_quizObjects.quiz_text }}</h2>
        </div>
    </div>
</body>

</html>

seminal2024/templates/main/quiz01.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>時事ニュースAIクイズ</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/newsquiz.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="content">
            <!-- タイトルに戻る -->
            <div id="back">
                <a href="{% url 'quiz_app:index' %}" id="clear_button">タイトルに戻る</a>
            </div>
            <div>
                <!-- 第〇問 -->
                <h2 id="quiz_counter">ここに入れるよ</h2>
            </div>
            <!-- クイズ本文-->
             <div class="p1" id="source_text">
                {{ data.source_text}}
            </div>
            <!-- クイズ問題文 -->
            <div class="p2">
                {{ data.quiz_text }}
            </div>
            <div class="select_list">
                <!-- 選択肢１ -->
                <p class="btn" id="select_1">
                    {{ data.correct }}
                </p>
                <!-- 選択肢２ -->
                <p class="btn" id="select_2">
                    {{ data.incorrect_1 }}
                </p>
                <!-- 選択肢３ -->
                <p class="btn" id="select_3">
                    {{ data.incorrect_2 }}
                </p>
            </div>
            <div class="correct_content">
                {% load static %}
                <img src="{% static 'img/correct.png' %}" alt="丸">
                <p>正解!</p>
            </div>
            <div class="incorrect_content">
                {% load static %}
                <img src="{% static 'img/incorrect.png' %}" alt="バツ">
                <p>不正解...</p>
            </div>
        </div>
        <div id="footer">
            <!-- 次の問題 -->
            <a href="{% url 'quiz_app:quiz' %}?change_data=True" class="next is_hidden" id="next_button">次の問題</a>
        </div>
    </div>
    {% load static %} <!-- JavaScriptファイル -->
    <script src="{% static 'js/quiz_counter.js' %}"></script> <!-- 問題数や正解数をカウントするするスクリプト -->
    <script src="{% static 'js/select_script.js' %}"></script> <!-- 選択肢に関するスクリプト -->
</body>

</html>

seminal2024/templates/main/quiz_detail.html
{% extends "base/base.html" %}
{% block body %}

    <h2>{{ quiz.quiz_text }}</h2>
    <p>正解 : {{ quiz.correct }}</p>
    <p>不正解1 : {{ quiz.incorrect_1 }}</p>
    <p>不正解2 : {{ quiz.incorrect_2 }}</p>
    <p>引用文 :<br> {{ quiz.source_text }}</p>
    <p>
        <a href="{{ quiz.source }}" target="_blank">{{ quiz.source }}</a>
    </p>

    <a href="{% url 'quiz_app:quiz_update' quiz.id %}">編集</a>
    <br>
    <a href="{% url 'quiz_app:page_list' %}">クイズ一覧</a>
    <br>
    <a href="{% url 'quiz_app:index' %}">タイトルに戻る</a>
{% endblock %}

seminal2024/templates/main/quiz_list.html
{% extends "base/base.html" %}
{% block body %}
    <ol>
        {% for page in page_list %}
            <li>
                <a href="{% url 'quiz_app:quiz_detail' page.id %}">{{ page.quiz_text }}</a>
            </li>
        {% empty %}
        <h2>クイズが入ってません</h2>
        {% endfor %}
    </ol>
    <a href="{% url 'quiz_app:index' %}">タイトル</a>

{% endblock %}

seminal2024/templates/main/quiz_result.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>クイズ結果</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/quiz_result.css' %}">
</head>

<body>
    <div class="container">
        <div class="content">
            <h1 class="page_title">結果発表</h1>
            <div class="result">
                <p class="all_count"></p>
                <p class="correct"><span class="correct_num"></span>問正解!!</p>
                <p class="incorrect"></p>
            </div>
            <h2 class="message">何かメッセージ入れたい</h2>
        </div>
        <div id="footer">
            <!-- タイトルに戻る -->
            <div id="back">
                <a href="{% url 'quiz_app:index' %}" id="clear_button">タイトルに戻る</a>
            </div>
        </div>
    </div>
    {% load static %}
    <script src="{% static 'js/quiz_result.js' %}"></script>
</body>

</html>

seminal2024/templates/main/quiz_update.html
{% extends 'base/base.html' %}
{% block body %}
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">更新</button>
    </form>
{% endblock %}

seminal2024/templates/main/registration_quiz.html
{% extends 'base/base.html' %}
{% block body %}
    <p>ここでクイズ情報を登録するよ！</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ registration.as_p }}
        <button type="submit">保存</button>
    </form>
    <a href="{% url 'quiz_app:index' %}">タイトル</a>
{% endblock %}